In [1]:
#   Demonstration of numpy array vs a list

'''numpy array is 1.Faster,2.Takes less space,3.More convinient'''

import sys
import numpy as np
import time

l = range(1000) #Creates a list of 1000 elements 
print(sys.getsizeof(5)*len(l)) #Checks the total space taken by a list

a = np.arange(1000) #arage is used same as range but serves two purposes, creates an array and sets range also

print(a.size*a.itemsize) #Size is for the entire array and itemsize is size of one element

#In a numpy array each element is holding 4 bytes and in a list it occupies 14 bytes. Hence why numpy takes less space



28000
4000


In [5]:
#Demonstration of numpy vs list wrt speed
import numpy as np
import time
import sys

SIZE = 1000000

l1 = range(SIZE) #List
l2 = range(SIZE)

a1 = np.arange(SIZE) #Array
a2 = np.arange(SIZE)

#Python List
start = time.time()
result = [(x + y) for x,y in zip(l1,l2)]

print("Python List took: ", (time.time() - start)*1000)

#Numpy Array
start = time.time()
result = a1 + a2
print("Numpy array took: ", (time.time() - start)*1000) #   Takes 12 seconds for millions of values


#Another advantage of numpy array is that you can add, subtract, multiply or divide any 2 numpy arrays easily


Python List took:  100.1443862915039
Numpy array took:  12.258291244506836


In [14]:
#Array operations using numpy

import numpy as np

#1-D Array

a = np.array([1,2,3])  

#2-D Array

two_d = np.array([[1,2],[3,4],[5,6]])   # [1 2 
                                         # 3 4
                                         # 5 6] Displayed like this
print(f"Data Type: {two_d.dtype} No of Bytes: {two_d.itemsize}") #Int and 4

#a.ndim - Used to print the dimension of the array

#a.itemsize - Returns size of each element in np array

#a.dtype - Returns data type used in np array

#int- 4 bytes, float64- 8 bytes

a2 = np.array([1,2,3,4],dtype = np.float64) #Converts element into float

print(f"Data Type: {a2.dtype} No of Bytes: {a2.itemsize}")

#a.size - Total elements in the array

#a.shape - Returns the total rows and columns (rows,columns) like this

print(two_d.shape)

#np.zeros(rows,col)[shape of the array])-  Will return a array/matrix of 0's 

print(np.zeros((4,4)))

#np.ones- Can use for array of ones; Similar to array of zeros

#np.arange - Similar to range func where the last number isnt included
# Note: np.arange(start,end(not included in array),jump) jump is if you want to skip elements in between

#np.linspace(start,stop,num='') Creates an array of start to stop with a linear spacing of certain gap

#If i want an array of 5 numbers between 1 and 5 which is randomly chosen then

print(np.linspace(1,5,10))
 
#a.reshape- helps to change dimensions of the array as per your wish

#a.ravel() - Flatten an array
a3 = np.array([[1,2],[3,4],[5,6]])
print(a3.ravel())

#a.min()- prints minimum element

#a.max() - prints maximum element

#a.sum() - Prints sum of the array elements

#axis0 - All the columns are checked induvidually

#axis1 - All rows are checked induvidually

print(a3.sum(axis = 0)) #Adds each column seperately and generates result

#Returns [9 12]

#np.sqrt(array_name) - Returns square root of each of the array elements

#np.std(array_name) - Finds standard deviation of all these numbers

#array1.dot(array2) - Will give dot product of array_1 and array_2


Data Type: int32 No of Bytes: 4
Data Type: float64 No of Bytes: 8
(3, 2)
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]
[1 2 3 4 5 6]
[ 9 12]


In [31]:
#numpy Stacking/Slicing Arrays and Indexing

a = np.array([1,2,3,4,5,6])

#Lets print only first 4 elements

print(a[0:4]) 

#a[-1] will print last element

#Just like how matrices work as aij we can simply give a[i,j] and it will return that element

'''Create an array  A =[ 1 2 3
                         4 5 6
                         7 8 9 ]

And print a22 element 9
'''

array = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(array[2,2])

#We can iterate through rows and columns 

for row in array:
    print(row)

#We can print each cell
    
for cell in array.flat:
    print(cell)

#We can stack arrays together using vstack and hstack
    
#for Example

a = np.arange(1,7).reshape(3,2)
b = np.arange(7,13).reshape(3,2)

print(np.vstack((a,b)))

print(np.hstack((a,b)))

#You can split arrays using hsplit and vsplit command

c = np.arange(30).reshape(2,15)

result = np.hsplit(c,3)  #Will split c matrix into 3 seperate matrices
#We can print each inducividal split

for i in range(0,3):
    print(f"Result[{i}] is \n{result[i]}")


[1 2 3 4]
9
[1 2 3]
[4 5 6]
[7 8 9]
1
2
3
4
5
6
7
8
9
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
[[ 1  2  7  8]
 [ 3  4  9 10]
 [ 5  6 11 12]]
Result[0] is 
[[ 0  1  2  3  4]
 [15 16 17 18 19]]
Result[1] is 
[[ 5  6  7  8  9]
 [20 21 22 23 24]]
Result[2] is 
[[10 11 12 13 14]
 [25 26 27 28 29]]


In [39]:
#Boolean Arrays

#We can convert an entire numpy array in terms of boolean values to check for True or False

a = np.arange(9).reshape(3,3)
print(a)

bool = a <= 5 
print(bool) #Prints the array and shows true for elements < 5

print(a[bool]) #Returns all true elements


[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ True  True  True]
 [ True  True  True]
 [False False False]]
[0 1 2 3 4 5]


In [5]:
import numpy as np
#Numpy nidter concept

#There are two types of order we can use in np.nditer

#1. C order- [1 2 3, 4 5 6,7 8 9] in C order will be in row order

#2.Fortran order- [1 2 3 , 4 5 6, 7 8 9] in fortran order will be column wise

a = np.arange(12).reshape(3,4)

for x in np.nditer(a,order = 'F'):
    print(x)

#If you wanna display each column iteration seperately also then its possible using flags arguement
    
for x in np.nditer(a,order='F',flags = ['external_loop']):
    print(x)

0
4
8
1
5
9
2
6
10
3
7
11
[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]
