1. Functions Used In NumPy

In [5]:
import numpy as np 

#Creating an ndarray

data = [5,6,7,7.75,8]

arr =  np.array(data,dtype = float) #This will convert the list into a simple 1-D numpy array
print(f"Numpy array is:{arr} and its dimension is {arr.ndim}") #ndim represents the overall dimension of the array(1-D,2-D,3-D and so on...)

#2-D numpy arrays

data2 = [[1,2,3],[4,5,6]] #If elements are equal then you can create a 2-D numpy array

arr2 = np.array(data2,dtype=complex).reshape(3,2)
print(f"Original Dimension was {np.array(data2).shape} But arr2 dimension is reshaped to {arr2.shape}")
print(arr2)


Numpy array is:[5.   6.   7.   7.75 8.  ] and its dimension is 1
Original Dimension was (2, 3) But arr2 dimension is reshaped to (3, 2)
[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]
 [5.+0.j 6.+0.j]]


In [21]:
#Additionaly we can create arrays of 0's and 1's as well

zeros = np.zeros(10).reshape(5,2) #Creates a numpy 0 array of 10 elements 
#We can also simplify this as np.zeros(5,2) and the result will be same

print(zeros,'\n')

ones = np.ones(15).reshape(3,5) #Creates a 3x5 2-D Array Of 1's
print(ones,'\n')

#To create a numpy array of uninitialized garbage values, you can use empty arrays

empty = np.empty((5,3,2)) #To create Higher-dimensional arrays i.e >2 we can add an additional tuple here
print(empty)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]] 

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]] 

[[[1.35260925e-311 1.01283457e-321]
  [0.00000000e+000 0.00000000e+000]
  [6.23058028e-307 1.16097020e-028]]

 [[1.26104862e-076 2.04380493e-028]
  [8.59810802e-067 1.04917183e-153]
  [5.23081515e-143 1.04784554e+165]]

 [[5.55269641e+170 5.09691828e-066]
  [1.74164439e+184 8.13520945e-144]
  [3.59751658e+252 1.46901661e+179]]

 [[8.37404147e+242 4.31999013e-096]
  [4.82337723e+228 3.73603744e-061]
  [1.51818374e-051 5.64165036e-091]]

 [[7.96662932e-042 1.53645074e-051]
  [5.04621343e+180 1.94918963e-153]
  [1.14484251e+243 2.59903827e-144]]]


In [28]:
#We can also derive a specific range of numbers to be displayed in out numpy array using 'arange' function

ranged = np.arange(15).reshape(3,5) #Creates an array with 15 elements numbered 0 to 14 because range is from 0 to n-1

print(ranged,'\n')

np.identity((4)) #Creates an identity matrix of nxn dimension (They can be converted/reshaped to another possible product dimension. eg: 16 = 4x4 or 8x2)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]] 



array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [47]:
#Simple multiplication of 2-D arrays

l1 = []
m = int(input('Enter the number of elements: '))
for i in range(m):
    inp1 = int(input())
    l1.append(inp1)
print(l1)

a = np.asarray(l1) #Converts the list into ndarray

l2 = [5,4,3,2,1]
b = np.asarray(l2)
print(b)

print(f"The dot product of the two converted list to array is:\n{np.dot(a,b)}") #Performs dot product of the two matrices

#Note: ones_like and zeros_like will generate a similar array of before(if ones and zeroes were used) of the same shape and size


Enter the number of elements:  5
 1
 2
 3
 4
 5


[1, 2, 3, 4, 5]
[5 4 3 2 1]
The dot product of the two converted list to array is:
35


In [52]:
#You can change the type of data of an nd array using astype

a1 = np.array([1.54,2.22,3.33,4.44,5.55,6.66],dtype = int).reshape(3,2)
print(f"Array as an int:\n{a1}")
a2 = np.array(a).astype(float)
print(f"Array as an float64:\n{a2}")

Array as an int:
[[1 2]
 [3 4]
 [5 6]]
Array as an float64:
[1. 2. 3. 4. 5.]


2. Scalar Operations in NumPy

In [65]:
arr = np.array([1,2,3,4]).reshape(2,2)
print(f"Original Array:\n{arr}")
print(f"Array Self Product: i.e \narr*arr=\n{arr*arr}")
print(f"arr-arr =\n{arr-arr}")

Original Array:
[[1 2]
 [3 4]]
Array Self Product: i.e 
arr*arr=
[[ 1  4]
 [ 9 16]]
arr-arr =
[[0 0]
 [0 0]]


3. Basic Indexing and Slicing

In [72]:
#Slicing of 1-D Arrays

arr = np.arange(10) # [1 2 3 4 5 6 7 8 9 10]

print(arr[:5]) #Prints from arr[0] to arr[4]

print(arr[4:7]) #Prints from arr[4] to arr[6]

print(f"Array Before updation:\n{arr}")

#The trend noticed in slicing is that the left index is included and the right is not included

arr[4:6] =16 #arr[4] and arr[5] are changed to 16

print(f"Array After updation:\n{arr}")

#Note that arrays arent copied when sliced. Hence if you want to store a copy of the array use .copy() fucntion along with slicing

[0 1 2 3 4]
[4 5 6]
Array Before updation:
[0 1 2 3 4 5 6 7 8 9]
Array After updation:
[ 0  1  2  3 16 16  6  7  8  9]


In [74]:
#Slicing of 2-D Arrays

#In Higher Dimensional arrays, every index is atleast a 1-D array, Hence opening up to more possibilities

arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) #arr[0] is [1 2 3] arr[1] is [4 5 6] and arr[2] is [7 8 9]

print(arr2d[:2]) #Prints only first 2 rows

[[1 2 3]
 [4 5 6]]
